name: yuletide_team_mate_composer
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: 3.16.5

dependencies:
  flutter:
    sdk: flutter

  #General
  injectable: 2.3.2
  get_it: 7.6.4
  flutter_bloc: 8.1.3
  freezed: 2.4.6
  flutter_hooks: 0.20.4

  #Utils
  hooked_bloc: 1.4.3
  fimber_io: 0.7.0

  #UI
  flutter_svg: 2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  analyzer: 5.13.0
  build_runner: 2.4.7
  injectable_generator: 2.4.1
  freezed_annotation: 2.4.1
  flutter_gen_runner: 5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/generated/assets/
  integrations:
    flutter_svg: true